# welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7]], np.int64)

In [3]:
myarr

array([[ 3,  6, 37,  7]], dtype=int64)

In [4]:
myarr[0,1]

6

In [5]:
myarr[0]

array([ 3,  6, 37,  7], dtype=int64)

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr[0,1] = 45

In [9]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

# array creation

In [10]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({34,23,32})

array({32, 34, 23}, dtype=object)

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,3,4)

In [21]:
lspace

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [22]:
emp = np.empty((4,6))

In [23]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.86919378e-306, 6.23060744e-307, 8.90105597e-307],
       [6.23053614e-307, 7.56592338e-307, 1.60220528e-306,
        7.56602523e-307, 1.42417221e-306, 1.37961641e-306],
       [2.22522597e-306, 1.33511969e-306, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        2.13620807e-306, 1.69118787e-306, 2.56765117e-312]])

In [24]:
emp_like = np.empty_like(lspace)

In [25]:
emp_like

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [26]:
ide = np.identity(45)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

In [29]:
arr = np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr = arr.reshape(3,33)

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr = arr.ravel()

In [34]:
arr.shape

(99,)

# Axis

In [35]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [36]:
ar = np.array(x)

In [37]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
ar.sum(axis=0)

array([12,  8,  9])

In [39]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [40]:
ar.ravel().sum(axis=0)

29

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [42]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
ar.flat

In [45]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [46]:
for item in ar.ravel():
    print(item)

1
2
3
4
5
6
7
1
0


In [47]:
for item in ar:
    print(item)

[1 2 3]
[4 5 6]
[7 1 0]


In [48]:
ar.ndim

2

In [49]:
ar.size


9

In [51]:
ar.nbytes

36

In [52]:
one = np.array([1,3,4,638,2])

In [53]:
one.argmax()

3

In [54]:
one[one.argmax()]

638

In [55]:
one.argmin()

0

In [56]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [59]:
for i in one.argsort():
    print(one[i],end=" ")

1 2 3 4 638 

In [60]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
ar.argmin()

8

In [69]:
ar.argmax()

6

In [63]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [65]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [66]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [67]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [70]:
ar.ravel()


array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [73]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [75]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [76]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [77]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [78]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [79]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [80]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [81]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [82]:
ar.sum()

29

In [83]:
ar.max()

7

In [84]:
ar.min()

0

In [85]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [88]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [89]:
np.count_nonzero(ar)

8

In [90]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [91]:
ar[1,2] = 0

In [92]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [93]:
import sys

In [94]:
py_ar = [0,4,55,2]

In [95]:
np_ar = np.array(py_ar)

In [96]:
sys.getsizeof(1)*len(py_ar)

112

In [97]:
np_ar.itemsize * np_ar.size

16

In [98]:
np_ar.tolist()

[0, 4, 55, 2]